export const GET_ALL_RENTAL = 'GET_ALL_RENTAL';
export const GET_ALL_RENTAL_BY_STATUS = 'GET_ALL_RENTAL_BY_STATUS';
export const CREATE_RENTAL = 'CREATE_RENTAL';
export const UPDATE_RENTAL = 'UPDATE_RENTAL';
export const DELETE_RENTAL = 'DELETE_RENTAL';
export const CANCEL_RENTAL = 'CANCEL_RENTAL';