export const GET_ALL_SERVICE_CONTRACT = 'GET_ALL_SERVICE_CONTRACT';
export const CREATE_SERVICE_CONTRACT = 'CREATE_SERVICE_CONTRACT';
export const UPDATE_SERVICE_CONTRACT = 'UPDATE_SERVICE_CONTRACT';
export const DELETE_SERVICE_CONTRACT = 'DELETE_SERVICE_CONTRACT';
